"""Add report schedule configs table

Revision ID: 5266dc3b9a24
Revises: 
Create Date: 2025-09-06 19:06:52.106957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5266dc3b9a24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_schedule_configs',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.String(), nullable=False),
    sa.Column('schedule_time', sa.Time(), nullable=False),
    sa.Column('weekday', sa.String(), nullable=True),
    sa.Column('day_of_month', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('report_title_template', sa.String(), nullable=False),
    sa.Column('date_range_days', sa.String(), nullable=True),
    sa.Column('tags_filter', sa.JSON(), nullable=True),
    sa.Column('sources_filter', sa.JSON(), nullable=True),
    sa.Column('prompt_template_id', postgresql.UUID(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_recipients', sa.JSON(), nullable=True),
    sa.Column('email_subject_template', sa.String(), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_execution_status', sa.String(), nullable=True),
    sa.Column('last_execution_message', sa.String(), nullable=True),
    sa.Column('next_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_schedule_configs_created_at'), 'report_schedule_configs', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_schedule_configs_enabled'), 'report_schedule_configs', ['enabled'], unique=False)
    op.create_index(op.f('ix_report_schedule_configs_id'), 'report_schedule_configs', ['id'], unique=False)
    op.create_index(op.f('ix_report_schedule_configs_last_executed_at'), 'report_schedule_configs', ['last_executed_at'], unique=False)
    op.create_index(op.f('ix_report_schedule_configs_name'), 'report_schedule_configs', ['name'], unique=False)
    op.create_index(op.f('ix_report_schedule_configs_next_scheduled_at'), 'report_schedule_configs', ['next_scheduled_at'], unique=False)
    op.create_index(op.f('ix_report_schedule_configs_schedule_type'), 'report_schedule_configs', ['schedule_type'], unique=False)
    op.drop_index('idx_articles_scraped_date', table_name='articles')
    op.drop_index('idx_articles_title', table_name='articles')
    op.drop_index('idx_articles_url', table_name='articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_articles_url', 'articles', ['url'], unique=False)
    op.create_index('idx_articles_title', 'articles', ['title'], unique=False)
    op.create_index('idx_articles_scraped_date', 'articles', ['scraped_date'], unique=False)
    op.drop_index(op.f('ix_report_schedule_configs_schedule_type'), table_name='report_schedule_configs')
    op.drop_index(op.f('ix_report_schedule_configs_next_scheduled_at'), table_name='report_schedule_configs')
    op.drop_index(op.f('ix_report_schedule_configs_name'), table_name='report_schedule_configs')
    op.drop_index(op.f('ix_report_schedule_configs_last_executed_at'), table_name='report_schedule_configs')
    op.drop_index(op.f('ix_report_schedule_configs_id'), table_name='report_schedule_configs')
    op.drop_index(op.f('ix_report_schedule_configs_enabled'), table_name='report_schedule_configs')
    op.drop_index(op.f('ix_report_schedule_configs_created_at'), table_name='report_schedule_configs')
    op.drop_table('report_schedule_configs')
    # ### end Alembic commands ###