"""add_password_change_required_column

Revision ID: 68c41c5891a7
Revises: 9bdd6b614e47
Create Date: 2025-09-07 14:59:11.213538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c41c5891a7'
down_revision = '9bdd6b614e47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_change_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_change_required')
    # ### end Alembic commands ###