"""Add RSS schedule table

Revision ID: 9bdd6b614e47
Revises: 5266dc3b9a24
Create Date: 2025-09-07 13:04:03.917265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bdd6b614e47'
down_revision = '5266dc3b9a24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('rss_file_path', sa.String(length=500), nullable=False),
    sa.Column('schedule_time', sa.Time(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_generate_tags', sa.Boolean(), nullable=False),
    sa.Column('skip_duplicates', sa.Boolean(), nullable=False),
    sa.Column('include_arxiv', sa.Boolean(), nullable=False),
    sa.Column('arxiv_categories', sa.Text(), nullable=True),
    sa.Column('arxiv_max_results', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rss_schedules_id'), 'rss_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_rss_schedules_user_id'), 'rss_schedules', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rss_schedules_user_id'), table_name='rss_schedules')
    op.drop_index(op.f('ix_rss_schedules_id'), table_name='rss_schedules')
    op.drop_table('rss_schedules')
    # ### end Alembic commands ###